description = "1日の業務を終了する (引数: 補足事項)"

prompt = """

# 1日の業務を終了する

1日の業務を終了する。
具体的には以下を実施する。

なお、その時々で、ユーザからの指示の補足が引数に与えられることがある。
有る場合は従う。

指示補足：{{args}}

## 1. 本日のサマリを本日分のworklogに記載する

本日のサマリセクションを作成し記載する。
情報源は以下とする
- Atlassian JiraやConfluenceで本日行っていた活動を収集
- Slack上で行っていた活動を収集
- MTGはGoogleカレンダーを参照する
- 本日分のworklogで本日行っていた活動を収集

内容は上記の情報源から読み取れる範囲で構わない。
ユーザがそれを叩き台に適宜修正を行う運用を想定する。

記載例は以下。
```
## 本日のサマリ

### 実施作業と工数

9:30 - 18:30 (休憩1h) = 8h

- 朝会: 0.5
- AAA定例: 1
- XXX 追加対応: 4
  - 実装: 3.5
  - 手動テストパターン作成: 0.5
- YYY: 0.5
  - PRレビュー: 0.5
- ZZZ 対応: 1.5
  - 資料レビュー: 1
  - MTG: 0.5
- 1on1: 0.5
```

補足
- worklogは~/work-repo/work-log/配下に存在する
- 工数は0.5h, 3hなど時単位で記載し、最小単位は0.25hとする
- 業務終了時間は15分単位で換算し切り上げとする。例は以下
  - 現在時刻が18:50の場合→18:45
  - 現在時刻が20:37の場合→20:30
- 業務開始時間が分からなければユーザに聞く
- 休憩は1h換算で良い
- 各作業の合計時間が、その日の業務時間になるようにする


## 2. 本日の~/work-repo内の変更内容を全てコミットする

コミットメッセージは、以下のような形式で統一する。

```
{yyyymmdd}

{コミット内容のサマリ}
```

以上。

"""
