
description = "Slackから最新情報を得る (引数: 情報を得たい対象)"

prompt = """
Slack MCPを使用して、引数で指定された内容({{args}})についての最新情報をまとめて出力する。

その際、元となった投稿をユーザが自分でも読めるように、投稿のリンクも最後に注釈として記載する。
以下が例

```
(略)

- xxxすることになった。[1]

(略)

[1] [yyyについての議論スレッド上のxxxについての投稿](https://my-org.slack.com/xxxxxxxx)
[2] [aaaについての作業スレッド]((https://my-org.slack.com/yyyyyyy)
```
"""
